# Generated by Django 2.2.2 on 2019-06-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfil', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=25)),
                ('login_atualizacao', models.CharField(max_length=150)),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=250)),
                ('ativo', models.CharField(max_length=1)),
                ('login_atualizacao', models.CharField(max_length=150)),
                ('data_atualizacao', models.DateTimeField()),
                ('cod_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('palavras_chave', models.CharField(max_length=200)),
                ('resumo', models.CharField(max_length=300)),
                ('texto', models.CharField(max_length=600)),
                ('prioridade', models.IntegerField()),
                ('link_externo', models.CharField(max_length=300)),
                ('link_foto', models.CharField(max_length=300)),
                ('link_audio', models.CharField(max_length=300)),
                ('link_video', models.CharField(max_length=300)),
                ('link_georreferenciamento', models.CharField(max_length=300)),
                ('login_atualizacao', models.CharField(max_length=150)),
                ('data_publicacao', models.DateTimeField()),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_app.Usuario')),
            ],
        ),
    ]
